### ISSUE TITLE
What will happen to `U256` when `as_u128` is non_zero in the uppermost `u64`?

### ISSUE THREAD

**Issue by leofisG** [pontem-network/U256#1]
https://github.com/pontem-network/U256/blob/62393739e8837d01a0f275ec24b521d56e3afcfe/sources/U256.move#L97

It seems like the uppermost `u64` is not checked, however, what if that is non-zero? The expected behaviour should be a failure right?

I would expect the implementation to be:
```
    public fun as_u128(a: U256): u128 {
        let a1 = *Vector::borrow(&a.ret, 0);
        let a2 = *Vector::borrow(&a.ret, 1);
        let z0 = *Vector::borrow(&a.ret, 2);
        let z1 = *Vector::borrow(&a.ret, 3);

        assert!(z0 == 0 && z1 == 0, EU128_OVERFLOW);

        ((a2 as u128) << 64) + (a1 as u128)
    }
```

**Comment by borispovod** [comment]
Hi @leofisG ,

Thank you for comment, you are right, i would appreciate a pull request.

**Comment by leofisG** [comment]
https://github.com/pontem-network/U256/pull/2

**Comment by borispovod** [comment]
@leofisG thanks!
